main_branch_name: main
stale_branch_threshold_days: 1
branch_prefixes:
  feature: feature_
  release: release_
  hotfix: hotfix_
automatic_tags:
  release_prefix: v
  hotfix_prefix: hotfix-tag_
lint:
  conventional_commit_type:
    enabled: true
    allowed_types:
    - build
    - chore
    - ci
    - docs
    - feat
    - fix
    - perf
    - refactor
    - revert
    - style
    - test
  issue_key_missing:
    enabled: false
    pattern: ^[A-Z]+-\d+$
  subject_line_rules:
    subject_line_max_length: 72
    subject_line_not_capitalized: true
    subject_line_no_period: true
  body_line_rules:
    body_max_line_length: 80
